'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TonConnectUIProvider } from '@tonconnect/ui-react';
import { createContext, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });
const GlobalContext = createContext('' as any);

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [openModal, setOpenModal] = useState(false);
  const [openMenu, setOpenMenu] = useState(false);

  const value = {
    openModal,
    setOpenModal,
    openMenu,
    setOpenMenu,
  };

  return (
    <html lang="en">
      <TonConnectUIProvider manifestUrl={process.env.NEXT_PUBLIC_TON_MANIFEST}>
        <GlobalContext.Provider value={value}>
          <body className={inter.className}>{children}</body>
        </GlobalContext.Provider>
      </TonConnectUIProvider>
    </html>
  );
}
